### ISSUE TITLE
Select field bug 

### ISSUE THREAD

**Issue by abbiecoghlan** [FlourishHealth/ferns-ui#90]
Select field has a bug when you'd like to select the first value in the drop down. It appears to be pre-selected with the first option, but the value is not actually set or updated.

**Comment by kjkurtz** [comment]
I believe this is fixed with the new controlled component version of `Field` or if you use `SelectList` directly. Can you confirm @abbiecoghlan?

**Comment by abbiecoghlan** [comment]
Yes, it is!!! I am almost positive Josh meant to add the other select but to this backlog which is that it's broken on android.
